/** Static brand assets exported from Figma Pideh-Dev (node 1:76). */
export const PIDEH_ASSETS = {
  logo: "/brand/pideh/logo.png",
  footerLogo: "/brand/pideh/footer-logo.svg",
  foodPide: "/brand/pideh/food-pide.png",
  ctaPide: "/brand/pideh/cta-pide.png",
  ctaDotA: "/brand/pideh/cta-dot-a.svg",
  ctaDotB: "/brand/pideh/cta-dot-b.svg",
  ctaDotC: "/brand/pideh/cta-dot-c.svg",
  ctaDotD: "/brand/pideh/cta-dot-d.svg",
  ctaDotE: "/brand/pideh/cta-dot-e.svg",
  ctaDotF: "/brand/pideh/cta-dot-f.svg",
  /** Optional Figma Kling export (51:133). Missing file → CSS float fallback. */
  heroVideoMp4: "/brand/pideh/hero-pide.mp4",
  heroVideoWebm: "/brand/pideh/hero-pide.webm",
  categoryPide: "/brand/pideh/category-pide.png",
  categoryArc: "/brand/pideh/category-arc.svg",
  waveYellow: "/brand/pideh/wave-yellow.svg",
  waveOrange: "/brand/pideh/wave-orange.svg",
  /** Figma Rectangle 6 (1:81) — CTA transition, same drip geometry as yellow waves. */
  waveOrangeCta: "/brand/pideh/wave-orange-cta.svg",
  /** Figma Rectangle 7 (1:202) — yellow footer band, asset 1510×540 with frame overflow. */
  waveFooter: "/brand/pideh/wave-footer.svg",
  featureWave: "/brand/pideh/feature-wave.svg",
  featureDelivery: "/brand/pideh/feature-delivery.png",
  featureQuality: "/brand/pideh/feature-quality.png",
  featureSupport: "/brand/pideh/feature-support.png",
  featurePrep: "/brand/pideh/feature-prep.png",
  arrowLeft: "/brand/pideh/arrow-left.svg",
  arrowRight: "/brand/pideh/arrow-right.svg",
  iconArrow: "/brand/pideh/icon-arrow.svg",
  socialInstagram: "/brand/pideh/social-1.svg",
  socialFacebook: "/brand/pideh/social-2.svg",
  socialTelegram: "/brand/pideh/social-3.svg",
  socialWhatsapp: "/brand/pideh/social-4.svg",
  socialViber: "/brand/pideh/social-5.svg",
} as const;
