/** Figma Mobile home (node 259:369) committed assets. */
export const MOBILE_HOME_ASSETS = {
  logo: "/brand/pideh/mobile/logo.png",
  menuUser: "/brand/pideh/mobile/menu-user.svg",
  headerDrip: "/brand/pideh/mobile/header-drip.svg",
  headerDripPng: "/brand/pideh/mobile/header-drip.png",
  ellipse3469: "/brand/pideh/mobile/ellipse-3469.svg",
  categoryHighlight: "/brand/pideh/mobile/category-highlight.svg",
  search: "/brand/pideh/mobile/search.svg",
  arrowLeft: "/brand/pideh/mobile/arrow-left.svg",
  arrowRight: "/brand/pideh/mobile/arrow-right.svg",
  catPide: "/brand/pideh/mobile/cat-pide.svg",
  catSnack: "/brand/pideh/mobile/cat-snack.svg",
  catSandwich: "/brand/pideh/mobile/cat-sandwich.svg",
  catDrink: "/brand/pideh/mobile/cat-drink.svg",
  catBurger: "/brand/pideh/mobile/cat-burger.svg",
  plus: "/brand/pideh/mobile/plus.svg",
  heartOutline: "/brand/pideh/mobile/heart-outline.svg",
  viewAllArrow: "/brand/pideh/mobile/view-all-arrow.svg",
  featurePath: "/brand/pideh/mobile/feature-path.svg",
  featureDelivery: "/brand/pideh/mobile/feature-delivery.png",
  featurePrep: "/brand/pideh/mobile/feature-prep.png",
  featureQuality: "/brand/pideh/mobile/feature-quality.png",
  featureSupport: "/brand/pideh/mobile/feature-support.png",
  branchPin: "/brand/pideh/mobile/branch-pin.png",
  phone: "/brand/pideh/mobile/phone.svg",
  navBar: "/brand/pideh/mobile/nav-dock.png",
  navEllipse: "/brand/pideh/mobile/nav-ellipse.svg",
  navEllipseDock: "/brand/pideh/mobile/nav-ellipse-dock.svg",
  navHome: "/brand/pideh/mobile/nav-home.svg",
  navChef: "/brand/pideh/mobile/nav-chef.svg",
  navCart: "/brand/pideh/mobile/nav-cart.svg",
  navHeart: "/brand/pideh/mobile/nav-heart.svg",
  navUser: "/brand/pideh/mobile/nav-user.svg",
} as const;
